---
name: AntiVPN
version: 2.0.3
api: 5.0.0
main: RajadorDev\AntiVPN
author: Rajador 
description: 'Protect your server of proxy.'
website: 'github.com/RajadorDev'
permissions:
  antivpn.command:
    description: 'AntiVPN admin command permission'
    default: op
  antivpn.command.secret:
    description: 'Set api key'
    default: op
  antivpn.command.whitelist:
    description: 'Manage whitelist'
    default: op
  antivpn.alert.receive:
    description: 'See alerts'
    default: op
  antivpn.bypass:
    description: 'Be ignored by AntiVPN System'
    default: false
...